DT-TSG_Web/Controllers/BookController.cs
using DTTSG_BLL.Book;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DTTSG_Web.Controllers
{
    public class BookController : Controller
    {
        BookManager bookManager = new BookManager();

        // GET: Book
        public ActionResult BookList()
        {
            ViewBag.BookList = bookManager.GetBookList();
            return View();
        }
    }
}

DT-TSG_Web/Controllers/BorrowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DTTSG_Web.Controllers
{
    public class BorrowController : Controller
    {
        // GET: Borrow
        public ActionResult BorrowList()
        {
            return View();
        }
    }
}

DT-TSG_Web/Controllers/CollectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DTTSG_Web.Controllers
{
    public class CollectController : Controller
    {
        // GET: Collect
        public ActionResult CollectList()
        {
            return View();
        }
    }
}

DT-TSG_Web/Controllers/ForwardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DTTSG_Web.Controllers
{
    public class ForwardController : Controller
    {
        // GET: Forward
        public ActionResult ForwardList()
        {
            return View();
        }
    }
}

DT-TSG_Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DT_TSG_Web.Controllers
{
    public class HomeController : Controller
    {
        #region 用户首页框架以及首页信息
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Default()
        {
            return View();
        }
        #endregion

        public ActionResult RankList()
        {
            return View();
        }
    }
}

DT-TSG_Web/Controllers/LoginController.cs
using DTTSG_BLL.User;
using DTTSG_Model;
using DTTSG_Model.ViewModel;
using RT.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DTTSG_Web.Controllers
{
    public class LoginController : Controller
    {
        UserLoginManager userLoginManager = new UserLoginManager();

        [HttpGet]
        /// <summary>
        /// 跳转用户登录页
        /// </summary>
        /// <returns>带模型的视图</returns>
        public ActionResult Login()
        {
            if (Request["userlogout"] != null)
            {
                Session.Remove("User");  //移除Session
            }
            
            //检测是否有用户在登录状态
            if (Session["User"] != null)
            {
                return Redirect("/Home/Index");
            }
            
            //返回强类型视图模型(不返回前端密码报错!)
            return View();
        }

        [HttpPost]
        /// <summary>
        /// 检查登录信息
        /// </summary>
        /// <returns>Ajax结果</returns>
        public ActionResult LoginCheck(LoginModel loginUser)
        {
            //实体模型验证
            if (ModelState.IsValid)
            {
                return LoginInfoCheck(loginUser);
            }
            //人机 or 实体模型 验证未通过
            return Json(new AjaxBackInfo(0, "表单数据不合法！"));
        }

        /// <summary>
        /// 用户信息查询
        /// </summary>
        /// <param name="loginUser"></param>
        /// <returns></returns>
        public JsonResult LoginInfoCheck(LoginModel loginUser)
        {
            //转换模型成数据模型并与数据库比较
            UserInfo loginmodel = userLoginManager.GetUserInfo(new UserInfo()
            {
                UserId = (int)loginUser.UserId,
                UserPwd = loginUser.PassWord
            });
            //检查可用状态且用户存在
            if (loginmodel != null)
            {
                if (!loginmodel.IsValid)    //检查用户状态
                {
                    return Json(new AjaxBackInfo(5, "您的账号已停用,请联系管理员！"));
                }
                //成功登录进入主页
                Session["User"] = loginmodel;    //设置Session状态
                return Json(new AjaxBackInfo(1, "欢迎您, " + loginmodel.UserName + " !"));
            }
            else
            {
                return Json(new AjaxBackInfo(4, "用户名或密码错误！"));
            }
        }
        


    }
}

DT-TSG_Web/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DTTSG_Web.Controllers
{
    public class MessageController : Controller
    {
        // GET: Message
        public ActionResult MessageList()
        {
            return View();
        }
    }
}

DT-TSG_Web/Views/Book/BookList.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BookList</title>
</head>
<body>
    <div> 
        图书列表
    </div>
</body>
</html>

DT-TSG_Web/Views/Borrow/BorrowList.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BorrowList</title>
</head>
<body>
    <div> 
        借阅信息
    </div>
</body>
</html>

DT-TSG_Web/Views/Collect/CollectList.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CollectList</title>
</head>
<body>
    <div> 
        收藏列表
    </div>
</body>
</html>

DT-TSG_Web/Views/Forward/ForwardList.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ForwardList</title>
</head>
<body>
    <div> 
        预约
    </div>
</body>
</html>

DT-TSG_Web/Views/Home/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>锐拓地铁图书管理系统</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta http-equiv="Access-Control-Allow-Origin" content="*">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">

    <link rel="icon" href="~/Content/images/favicon.ico">
    <link rel="stylesheet" href="~/lib/layui-v2.5.5/css/layui.css" media="all">
    <link rel="stylesheet" href="~/css/layuimini.css?v=2.0.4.2" media="all">
    <link rel="stylesheet" href="~/css/themes/default.css" media="all">
    <link rel="stylesheet" href="~/lib/font-awesome-4.7.0/css/font-awesome.min.css" media="all">
    @Styles.Render("~/Index_Css")
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style id="layuimini-bg-color"></style>
</head>

<body class="layui-layout-body layuimini-all">
    <div class="layui-layout layui-layout-admin">
        <div class="layui-header header">
            <div class="layui-logo layuimini-logo"></div>
            <div class="layuimini-header-content">
                <a>
                    <div class="layuimini-tool"><i title="展开" class="fa fa-outdent" data-side-fold="1"></i></div>
                </a>
                <!--电脑端头部菜单-->
                <ul class="layui-nav layui-layout-left layuimini-header-menu layuimini-menu-header-pc layuimini-pc-show"></ul>
                <!--手机端头部菜单-->
                <ul class="layui-nav layui-layout-left layuimini-header-menu layuimini-mobile-show">
                    <li class="layui-nav-item">
                        <a href="javascript:;"><i class="fa fa-list-ul"></i> 选择模块</a>
                        <dl class="layui-nav-child layuimini-menu-header-mobile"></dl>
                    </li>
                </ul>
                <ul class="layui-nav layui-layout-right">
                    <li class="layui-nav-item" lay-unselect>
                        <a href="javascript:;" data-refresh="刷新"><i class="fa fa-refresh"></i></a>
                    </li>
                    <li class="layui-nav-item mobile layui-hide-xs" lay-unselect>
                        <a href="javascript:;" data-check-screen="full"><i class="fa fa-arrows-alt"></i></a>
                    </li>
                    <li class="layui-nav-item layuimini-setting">
                        <a href="javascript:;">
                            <img src="~/Content/images/logo.png" class="layui-nav-img">@{
                                if (Session["User"] != null)
                                {@((Session["User"] as DTTSG_Model.UserInfo).UserName)}
                            }
                        </a>
                        <dl class="layui-nav-child">
                            <dd>
                                <a href="javascript:;" layuimini-content-href="page/user-setting.html" data-title="基本资料" data-icon="fa fa-gears"><span class="fa fa-user"></span>&nbsp;&nbsp;&nbsp;基本资料</a>
                            </dd>
                            <dd>
                                <a href="javascript:;" layuimini-content-href="page/user-password.html" data-title="修改密码" data-icon="fa fa-gears"><span class="fa fa-wrench"></span>&nbsp;&nbsp;修改密码</a>
                            </dd>
                            <dd>
                                <hr>
                            </dd>
                            <dd>
                                <a href="javascript:;" class="login-out"><span class="fa fa-sign-out"></span>&nbsp;&nbsp;退出登录</a>
                            </dd>
                        </dl>
                    </li>
                    <li class="layui-nav-item layuimini-select-bgcolor" lay-unselect>
                        <a href="javascript:;" data-bgcolor="配色方案"><i class="fa fa-ellipsis-v"></i></a>
                    </li>
                </ul>
            </div>
        </div>
        <!--无限极左侧菜单-->
        <div class="layui-side layui-bg-black layuimini-menu-left">
            <div class="user-photo userinfo">
                <a class="img" layuimini-href="/用户信息" target="_self" href="javascript:;">
                    <span>用户信息</span>
                    <img src="~/Content/images/logo.png" class="userAvatar">
                </a>
                <p>
                    <span class="userName">
                        @{
                            if (Session["User"] != null)
                            {@((Session["User"] as DTTSG_Model.UserInfo).UserName)}
                        }
                    </span>
                </p>
            </div>

            <ul class="layui-nav layui-nav-tree layui-left-nav-tree layui-this" id="multi_module_0">
                <li class="layui-nav-item menu-li layui-this "> <a layuimini-href="@Url.Action("Default","Home")" target="_self" href="javascript:;"> <i class="fa fa-home"></i> <span class="layui-left-nav"> 用户首页</span></a> </li>
                <li class="layui-nav-item menu-li  "> <a layuimini-href="@Url.Action("BookList","Book")" target="_self" href="javascript:;"> <i class="fa fa-book"></i> <span class="layui-left-nav"> 图书列表</span></a> </li>
                <li class="layui-nav-item menu-li  "> <a layuimini-href="@Url.Action("BorrowList","Borrow")" target="_self" href="javascript:;"> <i class="fa fa-clock-o"></i> <span class="layui-left-nav"> 借阅信息</span></a> </li>
                <li class="layui-nav-item menu-li  "> <a layuimini-href="@Url.Action("CollectList","Collect")" target="_self" href="javascript:;"> <i class="fa fa-star"></i> <span class="layui-left-nav"> 我的收藏</span></a> </li>

                <li class="layui-nav-item menu-li  " style="padding-top:15px">
                    <a href="javascript:;"> <i class="fa fa-snowflake-o"></i> <span class="layui-left-nav">其它</span><span class="layui-nav-more"></span></a>
                    <dl class="layui-nav-child ">
                        <dd class="menu-dd  ">
                            <a href="javascript:;" layuimini-href="@Url.Action("RankList","Home")" target="_self"> <i class="fa fa-bar-chart-o"></i> <span class="layui-left-nav"> 排行榜</span></a>
                        </dd>
                        <dd class="menu-dd  ">
                            <a href="javascript:;" layuimini-href="@Url.Action("MessageList","Message")" target="_self"> <i class="fa fa-bell-o"></i> <span class="layui-left-nav"> 公告栏</span></a>
                        </dd>
                        <dd class="menu-dd  ">
                            <a href="javascript:;" layuimini-href="@Url.Action("ForwardList","Forward")" target="_self"> <i class="fa fa-rss"></i> <span class="layui-left-nav"> 我的预约</span></a>
                        </dd>
                    </dl>
                </li>
                <span class="layui-nav-bar"></span>
            </ul>
        </div>
        <!--初始化加载层-->
        <div class="layuimini-loader">
            <div class="layuimini-loader-inner"></div>
        </div>
        <!--手机端遮罩层-->
        <div class="layuimini-make"></div>
        <!-- 移动导航 -->
        <div class="layuimini-site-mobile"><i class="layui-icon"></i></div>
        <!-- Tab和主体 -->
        <div class="layui-body">
            <div class="layuimini-tab layui-tab-rollTool layui-tab" lay-filter="layuiminiTab" lay-allowclose="true">
                <ul class="layui-tab-title">
                    <li class="layui-this" id="layuiminiHomeTabId" lay-id=""></li>
                </ul>
                <div class="layui-tab-control">
                    <li class="layuimini-tab-roll-left layui-icon layui-icon-left"></li>
                    <li class="layuimini-tab-roll-right layui-icon layui-icon-right"></li>
                    <li class="layui-tab-tool layui-icon layui-icon-down">
                        <ul class="layui-nav close-box">
                            <li class="layui-nav-item">
                                <a href="javascript:;"><span class="layui-nav-more"></span></a>
                                <dl class="layui-nav-child">
                                    <dd><a href="javascript:;" layuimini-tab-close="current">关 闭 当 前</a></dd>
                                    <dd><a href="javascript:;" layuimini-tab-close="other">关 闭 其 他</a></dd>
                                    <dd><a href="javascript:;" layuimini-tab-close="all">关 闭 全 部</a></dd>
                                </dl>
                            </li>
                        </ul>
                    </li>
                </div>

                <div class="layui-tab-content">
                    <div id="layuiminiHomeTabIframe" class="layui-tab-item layui-show"></div>
                </div>

            </div>
        </div>
    </div>

    <script src="~/lib/layui-v2.5.5/layui.js" charset="utf-8"></script>
    <script src="~/js/lay-config.js?v=2.0.0" charset="utf-8"></script>

    <script>
        layui.use(['jquery', 'layer', 'miniAdmin', 'miniTongji'], function () {
            var $ = layui.jquery,
                layer = layui.layer,
                miniAdmin = layui.miniAdmin,
                miniTongji = layui.miniTongji;

            var options = {
                iniUrl: "/Content/api/init.json",    // 初始化接口
                clearUrl: "/Content/api/clear.json", // 缓存清理接口
                urlHashLocation: true,      // 是否打开hash定位
                bgColorDefault: false,      // 主题默认配置
                multiModule: true,          // 是否开启多模块
                menuChildOpen: false,       // 是否默认展开菜单
                loadingTime: 0,             // 初始化加载时间
                pageAnim: true,             // iframe窗口动画
                maxTabNum: 20,              // 最大的tab打开数量
            };
            miniAdmin.render(options);

            // 百度统计代码，只统计指定域名
            miniTongji.render({
                specific: true,
                domains: [
                    '99php.cn'
                ],
            });

            $('.login-out').on("click", function () {
                layer.msg('退出登录成功', function () {
                    window.location = '/Login/Login/?userlogout=-1';
                });
            });
        });</script>
</body>
</html>

DT-TSG_Web/Views/Home/RankList.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>RankList</title>
</head>
<body>
    <div> 
        排行榜
    </div>
</body>
</html>

DT-TSG_Web/Views/Login/Login.cshtml
@{
    Layout = null;
}

@model DTTSG_Model.ViewModel.LoginModel

<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <title>图书管理系统 -- 用户登录</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta http-equiv="Access-Control-Allow-Origin" content="*">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
    @Styles.Render("~/Login_Css")
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="layui-container layui-anim layui-anim-up">
        <div class="admin-login-background">
            <div class="layui-form login-form">
                @using (Ajax.BeginForm("LoginCheck", "Login", new AjaxOptions()
                {
                    HttpMethod = "Post",
                    OnSuccess = "onSuccess(data, status, xhr)"
                }, new { @class = "layui-form" }))
                {
                    <div class="layui-form-item logo-title">
                        <h1>锐拓-地铁图书馆</h1>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-icon layui-icon-username" for="username"></label>
                        @Html.TextBoxFor(m => m.UserId,new {@class= "layui-input", @autocomplete = "off",
            @placeholder = "请输入用户名", @required = "required"} )
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-icon layui-icon-password" for="password"></label>
                        @Html.PasswordFor(m=>m.PassWord,new { @class = "layui-input", @autocomplete = "off",
            @placeholder = "请输入密码"})
                        <span class="bind-password fa fa-eye" id="icon-pas">
                            <img src="~/Content/images/show.png" id="icon-password"/>
                        </span>
                    </div>
                    <div class="layui-form-item">
                        <span style="padding-left:10px"><a href="#">用户注册</a></span>
                        <span style="padding-left:140px"><a href="#">忘记密码 ?</a></span>
                    </div>

                    <div class="layui-form-item">
                        <button class="layui-btn layui-btn layui-btn-normal layui-btn-fluid" lay-submit="" lay-filter="login">登 入</button>
                    </div>
                }
            </div>
        </div>
    </div>
    @Scripts.Render("~/Login_Js")
    
</body>
</html>

DT-TSG_Web/Views/Message/MessageList.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>MessageList</title>
</head>
<body>
    <div> 
        公告列表
    </div>
</body>
</html>